trigger:
  branches:
    include:
      - master
variables:
  imageName: 'tradecontrol'
  acrLoginServer: 'philipepompeu.azurecr.io'  # Altere conforme o seu
  dockerfilePath: 'Dockerfile'

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: UseDotNet@2
    inputs:
      packageType: 'sdk'
      version: '8.0.x'

  - script: dotnet restore
    displayName: 'Restaurar dependências'

  - script: dotnet build --configuration Release --no-restore
    displayName: 'Build'

  - task: Docker@2
    displayName: 'Build e Push Docker image'    
    inputs:
      command: 'buildAndPush'
      repository: '$(acrLoginServer)/$(imageName)'
      dockerfile: '$(dockerfilePath)'
      containerRegistry: 'ACR-Connection'
      tags: |
        latest
        $(Build.BuildId)
