services:
    postgres:
        image: postgres:15
        container_name: tradecontrol-db
        restart: always
        environment:
          POSTGRES_USER: tradecontrol
          POSTGRES_PASSWORD: tradecontrol
          POSTGRES_DB: tradecontrol
        volumes:
          - tradecontrolpg_data:/var/lib/postgresql/data
        ports:
          - "5433:5432" 
          
    tradeapi:
        build: ./
        ports:
            - "7068:8080" # formato HOST:CONTAINER
        environment:
          - ASPNETCORE_ENVIRONMENT=Production
          - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=tradecontrol;Username=tradecontrol;Password=tradecontrol
          - ASPNETCORE_URLS=http://0.0.0.0:8080
        depends_on:
         - postgres

    prometheus:
        image: prom/prometheus:latest
        container_name: tradecontrol-prometheus
        volumes:
            - ./prometheus.yml:/etc/prometheus/prometheus.yml
        command:
            - "--config.file=/etc/prometheus/prometheus.yml"
        ports:
            - "9090:9090"
        depends_on:
            - tradeapi

    grafana:
        image: grafana/grafana:latest
        container_name: tradecontrol-grafana
        ports:
            - "3000:3000"
        environment:
            - GF_SECURITY_ADMIN_USER=admin
            - GF_SECURITY_ADMIN_PASSWORD=admin
        restart: always
        depends_on:
            - prometheus
volumes:
  tradecontrolpg_data: